config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  devise_for :users, controllers: { registrations: "registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#home"

  get "profile" => "profile#index", as: :show_profile
  get "insurer" => "pages#insurer_home", as: :insurer_home
  get "policy/details" => "policy#index", as: :policy_details

  if Rails.env.development?
    namespace :api, defaults: { format: :json } do
      resources :policies, controllers: "policies_controller"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/policy.rb
class Policy < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum :role, { customer: "customer", insurer: "insurer", finance: "finance" }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_token.rb
class UserToken < ApplicationRecord
  belongs_to :user
end

app/controllers/api/policies_controller.rb
module Api
  class PoliciesController < ApiController
    before_action :set_policy, except: [:create, :index]

    def show
      render json: @policy
    end

    def index
      render json: @policy = Policy.all
    end

    def create
      @policy = Policy.create(policy_params)

      if @policy.save
        head :created, location: [:api, @policy]
      else
        render json: @policy.errors, status: :bad_entity
      end
    end
  end
end

app/controllers/api_controller.rb
# app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  include Pundit::Authorization
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def home
    if current_user.insurer?
      return redirect_to action: :insurer_home
    end

    authorize current_user, policy_class: CustomerPolicy
  end

  def insurer_home
    authorize current_user, policy_class: InsurerPolicy
  end
end

app/controllers/policy_controller.rb
class PolicyController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    authorize current_user, policy_class: CustomerPolicy
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, :only => [:create]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :name, :zipcode) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/policy_helper.rb
module PolicyHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <title><%= content_for(:title) || "Toosaint" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      Too Saint
    </a>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="/">
        Home
      </a>

      <% if user_signed_in? && current_user.customer? %>
        <%= link_to "Profile",  show_profile_path, class:"navbar-item"%>
      <% end %>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <% if !user_signed_in? %>
        <div class="buttons">
          <%= link_to "Sign up", new_registration_path("user"), class:"button is-primary" %><br />
          <%= link_to "Log in", new_session_path("user"), class:"button is-light" %>
        </div>
      <% end %>
      <% if user_signed_in? %>
        <div class="buttons">
          <%= link_to "Sign out", destroy_user_session_path, :method => "delete", data: { "turbo-method": :delete }, class:"button is-danger" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</nav>
    <div class="section">
      <div class="container">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}", class:"notification flash_#{name}" %>
        <% end %>

        <%= yield %>
      </div>
    </div>
    <script>
      const onload = () => {
        // Get all "navbar-burger" elements
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

        // Add a click event on each of them
        $navbarBurgers.forEach( el => {
          el.addEventListener('click', () => {

            // Get the target from the "data-target" attribute
            const target = el.dataset.target;
            const $target = document.getElementById(target);

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            el.classList.toggle('is-active');
            $target.classList.toggle('is-active');

          });
        });

      }
      document.addEventListener('DOMContentLoaded', onload);
      document.addEventListener('turbo:render', onload)
    </script>
  </body>
</html>

app/views/pages/home.html.erb
<nav class="level has-background-primary-light p-2">
  <!-- Left side -->
  <div class="level-left">
    <div class="level-item">
      <p class="title"><strong>Policies</strong></p>
    </div>
  </div>

  <!-- Right side -->
  <div class="level-right">
    <p class="level-item"><strong>All</strong></p>
    <p class="level-item"><a>Auto</a></p>
    <p class="level-item"><a>Health</a></p>
    <p class="level-item"><a class="button is-dark">New</a></p>
  </div>
</nav>
  <div class="is-flex is-flex-direction-column is-flex-wrap-wrap">
    <% (1..5).each do %>
      <div class="card m-2">
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <img
                  src="https://bulma.io/assets/images/placeholders/96x96.png"
                  alt="Placeholder image"
                />
              </figure>
            </div>

            <div class="media-content">
              <p class="title is-4">Auto Policy</p>
              <p class="subtitle is-6">provider</p>
            </div>
            <a href=<%= policy_details_path %>><span class="icon has-text-light">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>arrow-right-thin</title><path d="M14 16.94V12.94H5.08L5.05 10.93H14V6.94L19 11.94Z" /></svg>
              </span></a>
          </div>
            <div class="content">
              <div class="tag is-primary is-light is-medium">Monthly Premium : $20 </div>
              <div class="tag is-primary is-light is-medium">Coverage : $2000</div>
              <div class="tag is-info is-light is-medium">
                <time datetime="2016-1-1">1 Jan 2016</time>
              </div>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/insurer_home.html.erb
<h1 class="is-size-1">
  Insurer Home
</h1>

app/views/policy/index.html.erb
<div class="card">
  <header class="card-header">
    <h2 class="card-header-title is-size-3">Your Policy</h2>
    <button class="card-header-icon" aria-label="more options">
      <span class="icon">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </button>
  </header>
  <div class="card-content">
    <div class="content">
      <h4 class="has-text-primary">
        Plan Summary
      </h4>
      <p>Premium Health Cover</p>
      <h4 class="has-text-primary">
        Benefits Included
      </h4>
      <ol>
        <li>Hospitilization Coverage</li>
        <li>Ambulance Coverage</li>
        <li>Maternity Benefits</li>
        <li>Dental Coverage</li>
      </ol>
      <h4 class="has-text-primary">
        Plan Cost & Coverage
      </h4>
        <p>
        <span class="has-text-weight-semibold">
          Monthly Premium
        </span>
          $2000
        </p>
    </div>
  </div>
  <footer class="card-footer">
    <a href="#" class="card-footer-item">Modify</a>
  </footer>
</div>